device: /dev/ttyACM1
frame_id: gps
uart1:
  baudrate: 115200
config_on_startup: false

publish:
  all: true
  aid:
    hui: false

  nav:
    posecef: false

  rxm:
    raw: true

# raw data
raw_data: true
raw_data_stream:
  dir: /data/ubx_acm1
  publish: true
